# Generated by Django 5.1.4 on 2024-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
